#!/bin/sh
FLAVOR=Debug
APPNAME=UniversalEditor

if [ -d Output/$FLAVOR ]; then

	# running from git repository
	cd Output/$FLAVOR
	mono $APPNAME.exe ${1+"$@"}

else

	# installed to local machine
	mono $APPNAME.exe ${1+"$@"}

fi
