
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action FileNew;
	private global::Gtk.Action FileNewDocument;
	private global::Gtk.Action FileNewProject;
	private global::Gtk.Action FileOpen;
	private global::Gtk.Action FileOpenDocument;
	private global::Gtk.Action FileOpenProject;
	private global::Gtk.Action CloseAction;
	private global::Gtk.Action DocumentAction;
	private global::Gtk.Action ProjectAction;
	private global::Gtk.Action WindowAction;
	private global::Gtk.Action quitAction;
	private global::Gtk.Action EditAction;
	private global::Gtk.Action CutAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar1;
	private global::Gtk.Statusbar statusbar1;
	private global::Gtk.Label lblStatus;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action (
			"FileAction",
			global::Mono.Unix.Catalog.GetString("_File"),
			null,
			null
		);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_File");
		w1.Add (this.FileAction, null);
		this.FileNew = new global::Gtk.Action (
			"FileNew",
			global::Mono.Unix.Catalog.GetString("_New"),
			null,
			null
		);
		this.FileNew.ShortLabel = global::Mono.Unix.Catalog.GetString ("_New");
		w1.Add (this.FileNew, null);
		this.FileNewDocument = new global::Gtk.Action (
			"FileNewDocument",
			global::Mono.Unix.Catalog.GetString("_Document..."),
			null,
			null
		);
		this.FileNewDocument.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Document...");
		w1.Add (this.FileNewDocument, null);
		this.FileNewProject = new global::Gtk.Action (
			"FileNewProject",
			global::Mono.Unix.Catalog.GetString("_Project..."),
			null,
			null
		);
		this.FileNewProject.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Project...");
		w1.Add (this.FileNewProject, null);
		this.FileOpen = new global::Gtk.Action (
			"FileOpen",
			global::Mono.Unix.Catalog.GetString("_Open"),
			null,
			null
		);
		this.FileOpen.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Open");
		w1.Add (this.FileOpen, null);
		this.FileOpenDocument = new global::Gtk.Action (
			"FileOpenDocument",
			global::Mono.Unix.Catalog.GetString("_Document..."),
			null,
			null
		);
		this.FileOpenDocument.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Document...");
		w1.Add (this.FileOpenDocument, null);
		this.FileOpenProject = new global::Gtk.Action (
			"FileOpenProject",
			global::Mono.Unix.Catalog.GetString("_Project..."),
			null,
			null
		);
		this.FileOpenProject.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Project...");
		w1.Add (this.FileOpenProject, null);
		this.CloseAction = new global::Gtk.Action (
			"CloseAction",
			global::Mono.Unix.Catalog.GetString("_Close"),
			null,
			null
		);
		this.CloseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Close");
		w1.Add (this.CloseAction, null);
		this.DocumentAction = new global::Gtk.Action (
			"DocumentAction",
			global::Mono.Unix.Catalog.GetString("_Document"),
			null,
			null
		);
		this.DocumentAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Document");
		w1.Add (this.DocumentAction, null);
		this.ProjectAction = new global::Gtk.Action (
			"ProjectAction",
			global::Mono.Unix.Catalog.GetString("_Project"),
			null,
			null
		);
		this.ProjectAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Project");
		w1.Add (this.ProjectAction, null);
		this.WindowAction = new global::Gtk.Action (
			"WindowAction",
			global::Mono.Unix.Catalog.GetString("_Window"),
			null,
			null
		);
		this.WindowAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Window");
		w1.Add (this.WindowAction, null);
		this.quitAction = new global::Gtk.Action (
			"quitAction",
			global::Mono.Unix.Catalog.GetString("_Quit"),
			null,
			"gtk-quit"
		);
		this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Quit");
		w1.Add (this.quitAction, null);
		this.EditAction = new global::Gtk.Action (
			"EditAction",
			global::Mono.Unix.Catalog.GetString("_Edit"),
			null,
			null
		);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Edit");
		w1.Add (this.EditAction, null);
		this.CutAction = new global::Gtk.Action (
			"CutAction",
			global::Mono.Unix.Catalog.GetString("Cu_t"),
			null,
			null
		);
		this.CutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cu_t");
		w1.Add (this.CutAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Universal Editor");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menu name='FileNew' action='FileNew'><menuitem name='FileNewDocument' action='FileNewDocument'/><menuitem name='FileNewProject' action='FileNewProject'/></menu><menu name='FileOpen' action='FileOpen'><menuitem name='FileOpenDocument' action='FileOpenDocument'/><menuitem name='FileOpenProject' action='FileOpenProject'/></menu><menu name='CloseAction' action='CloseAction'><menuitem name='DocumentAction' action='DocumentAction'/><menuitem name='ProjectAction' action='ProjectAction'/><menuitem name='WindowAction' action='WindowAction'/></menu><menuitem name='quitAction' action='quitAction'/></menu><menu name='EditAction' action='EditAction'><menuitem name='CutAction' action='CutAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		this.statusbar1.HasResizeGrip = false;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.lblStatus = new global::Gtk.Label ();
		this.lblStatus.Name = "lblStatus";
		this.lblStatus.Xalign = 0F;
		this.lblStatus.LabelProp = global::Mono.Unix.Catalog.GetString ("Ready");
		this.statusbar1.Add (this.lblStatus);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.lblStatus]));
		w3.Position = 0;
		this.vbox1.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
