
// This file has been generated by the GUI designer. Do not modify.
namespace UniversalEditor.Editors.FileSystem
{
	public partial class FileSystemEditor
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.HBox hbox1;
		private global::Gtk.HPaned hpaned1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView tvFolders;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Toolbar tbBreadcrumb;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TreeView tvFiles;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget UniversalEditor.Editors.FileSystem.FileSystemEditor
			Stetic.BinContainer w1 = global::Stetic.BinContainer.Attach (this);
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup ("Default");
			this.UIManager.InsertActionGroup (w2, 0);
			this.Name = "UniversalEditor.Editors.FileSystem.FileSystemEditor";
			// Container child UniversalEditor.Editors.FileSystem.FileSystemEditor.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 203;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvFolders = new global::Gtk.TreeView ();
			this.tvFolders.CanFocus = true;
			this.tvFolders.Name = "tvFolders";
			this.GtkScrolledWindow.Add (this.tvFolders);
			this.hpaned1.Add (this.GtkScrolledWindow);
			global::Gtk.Paned.PanedChild w4 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.GtkScrolledWindow]));
			w4.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='tbBreadcrumb'/></ui>");
			this.tbBreadcrumb = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/tbBreadcrumb")));
			this.tbBreadcrumb.Name = "tbBreadcrumb";
			this.tbBreadcrumb.ShowArrow = false;
			this.vbox3.Add (this.tbBreadcrumb);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.tbBreadcrumb]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.tvFiles = new global::Gtk.TreeView ();
			this.tvFiles.CanFocus = true;
			this.tvFiles.Name = "tvFiles";
			this.GtkScrolledWindow1.Add (this.tvFiles);
			this.vbox3.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow1]));
			w7.Position = 1;
			this.hpaned1.Add (this.vbox3);
			this.hbox1.Add (this.hpaned1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hpaned1]));
			w9.Position = 0;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			w1.SetUiManager (UIManager);
			this.Hide ();
		}
	}
}
