using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UniversalEditor.IO;
using UniversalEditor.ObjectModels.FileSystem;

namespace UniversalEditor.DataFormats.FileSystem.LHA
{
	public class LHADataFormat : DataFormat
	{
		private static DataFormatReference _dfr = null;
		protected override DataFormatReference MakeReferenceInternal()
		{
			if (_dfr == null)
			{
				_dfr = base.MakeReferenceInternal();
				_dfr.Capabilities.Add(typeof(FileSystemObjectModel), DataFormatCapabilities.All);
			}
			return _dfr;
		}

		protected override void LoadInternal(ref ObjectModel objectModel)
		{
			FileSystemObjectModel fsom = (objectModel as FileSystemObjectModel);
			if (fsom == null) throw new ObjectModelNotSupportedException();

			Reader reader = base.Accessor.Reader;
			while (!reader.EndOfStream)
			{
				byte headerSize = reader.ReadByte();
				byte headerChecksum = reader.ReadByte();

				if (headerSize == 128 && headerChecksum == 0 && reader.PeekByte() == 0)
				{
					// why is there a 0x80, 0x00, 0x00 at the end of the file (at least generated by IZArc)?
					break;
				}

				string compressionMethod = reader.ReadFixedLengthString(5);
				uint compressedSize = reader.ReadUInt32();
				uint decompressedSize = reader.ReadUInt32();
				uint originalFileDateTime = reader.ReadUInt32();
				byte fileOrDirectoryAttribute = reader.ReadByte();
				byte levelIdentifier = reader.ReadByte();
				byte fileNameLength = reader.ReadByte();
				string fileName = reader.ReadFixedLengthString(fileNameLength);
				short crc = reader.ReadInt16();

				long offset = base.Accessor.Position;
				base.Accessor.Seek(compressedSize, SeekOrigin.Current);

				File file = fsom.AddFile(fileName);
				file.Size = decompressedSize;
				file.Properties.Add("reader", reader);
				file.Properties.Add("CompressedSize", compressedSize);
				file.Properties.Add("DecompressedSize", decompressedSize);
				file.Properties.Add("CompressionMethod", compressionMethod);
				file.Properties.Add("FileAttribute", fileOrDirectoryAttribute);
				file.Properties.Add("offset", offset);
				file.DataRequest += file_DataRequest;
			}
		}

		private void file_DataRequest(object sender, DataRequestEventArgs e)
		{
			File file = (sender as File);
			Reader reader = (Reader)file.Properties["reader"];
			uint compressedSize = (uint)file.Properties["CompressedSize"];
			uint decompressedSize = (uint)file.Properties["DecompressedSize"];
			string compressionMethod = (string)file.Properties["CompressionMethod"];
			byte fileAttribute = (byte)file.Properties["FileAttribute"];
			long offset = (long)file.Properties["offset"];

			reader.Seek(offset, SeekOrigin.Begin);
			byte[] compressedData = reader.ReadBytes(compressedSize);
			byte[] decompressedData = compressedData;
			switch (compressionMethod)
			{
				case "-lh0-":
				{
					// store, no compression
					decompressedData = compressedData;
					break;
				}
			}
			e.Data = decompressedData;
		}

		protected override void SaveInternal(ObjectModel objectModel)
		{
			FileSystemObjectModel fsom = (objectModel as FileSystemObjectModel);
			if (fsom == null) throw new ObjectModelNotSupportedException();

			Writer writer = base.Accessor.Writer;
			File[] files = fsom.GetAllFiles();
			foreach (File file in files)
			{
				byte headerSize = 34;
				writer.WriteByte(headerSize);
				byte headerChecksum = 0;
				writer.WriteByte(headerChecksum);

				string compressionMethod = "-lh0-";
				writer.WriteFixedLengthString(compressionMethod);

				byte[] decompressedData = file.GetDataAsByteArray();
				byte[] compressedData = decompressedData;
				switch (compressionMethod)
				{
					case "-lh0-":
					{
						break;
					}
				}

				DateTime originalFileDateTime = DateTime.Today;
				writer.WriteUInt32((uint)compressedData.Length);
				writer.WriteUInt32((uint)decompressedData.Length);
				writer.WriteUInt32((uint)0); // original file date/time
				byte fileOrDirectoryAttribute = 32;
				writer.WriteByte(fileOrDirectoryAttribute);

				byte levelIdentifier = 0;
				writer.WriteByte(levelIdentifier);

				byte fileNameLength = (byte)file.Name.Length;
				string fileName = file.Name.Substring(0, Math.Min(file.Name.Length, fileNameLength));
				writer.WriteByte(fileNameLength);
				writer.WriteFixedLengthString(fileName);

				short crc = 0;
				writer.WriteInt16(crc);

				writer.WriteBytes(compressedData);
			}

			writer.WriteByte(128);
			writer.WriteByte(0);
			writer.WriteByte(0);
		}
	}
}
