
// This file has been generated by the GUI designer. Do not modify.
namespace UniversalEditor.Engines.GTK.Dialogs
{
	public partial class AboutDialog
	{
		private global::Gtk.VBox vbox3;
		private global::Gtk.Image picLogo;
		private global::Gtk.Label label1;
		private global::Gtk.Label lblVersion;
		private global::Gtk.Notebook tbsTabs;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TextView txtApplicationInformation;
		private global::Gtk.Label label9;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView txtApplicationLicense;
		private global::Gtk.Label label3;
		private global::Gtk.HPaned hpaned2;
		private global::Gtk.ScrolledWindow GtkScrolledWindow5;
		private global::Gtk.TreeView tvComponents;
		private global::Gtk.Notebook notebook2;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Label label13;
		private global::Gtk.Label label12;
		private global::Gtk.ScrolledWindow GtkScrolledWindow4;
		private global::Gtk.TextView textview5;
		private global::Gtk.Label label6;
		private global::Gtk.ScrolledWindow GtkScrolledWindow3;
		private global::Gtk.TreeView tvComponentContributors;
		private global::Gtk.Label label7;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.TextView txtComponentLicense;
		private global::Gtk.Label label8;
		private global::Gtk.Label label11;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget UniversalEditor.Engines.GTK.Dialogs.AboutDialog
			this.Name = "UniversalEditor.Engines.GTK.Dialogs.AboutDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("About [ApplicationTitle]");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			// Internal child UniversalEditor.Engines.GTK.Dialogs.AboutDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.picLogo = new global::Gtk.Image ();
			this.picLogo.Name = "picLogo";
			this.vbox3.Add (this.picLogo);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.picLogo]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("<big><big><big><b>Universal Editor</b></big></big></big>");
			this.label1.UseMarkup = true;
			this.vbox3.Add (this.label1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label1]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.lblVersion = new global::Gtk.Label ();
			this.lblVersion.Name = "lblVersion";
			this.lblVersion.LabelProp = global::Mono.Unix.Catalog.GetString ("Version 1.0");
			this.vbox3.Add (this.lblVersion);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.lblVersion]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.tbsTabs = new global::Gtk.Notebook ();
			this.tbsTabs.CanFocus = true;
			this.tbsTabs.Name = "tbsTabs";
			this.tbsTabs.CurrentPage = 0;
			// Container child tbsTabs.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.txtApplicationInformation = new global::Gtk.TextView ();
			this.txtApplicationInformation.Buffer.Text = "Universal Editor is a cross-platform, Free Software modular document editor. Anyone can write plugins that provide new DataFormats, ObjectModels, and Accessors for use with the Universal Editor Platform. The Universal Editor Platform can be customized to meet your specific needs.\n\nThis implementation of the Universal Editor Platform is primarily developed and supported by Michael Becker with contributions from other Free Software developers. See the Components tab for information on individual contributors to various Universal Editor Platform components.";
			this.txtApplicationInformation.CanFocus = true;
			this.txtApplicationInformation.Name = "txtApplicationInformation";
			this.txtApplicationInformation.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow1.Add (this.txtApplicationInformation);
			this.tbsTabs.Add (this.GtkScrolledWindow1);
			// Notebook tab
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Information");
			this.tbsTabs.SetTabLabel (this.GtkScrolledWindow1, this.label9);
			this.label9.ShowAll ();
			// Container child tbsTabs.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.txtApplicationLicense = new global::Gtk.TextView ();
			this.txtApplicationLicense.CanFocus = true;
			this.txtApplicationLicense.Name = "txtApplicationLicense";
			this.GtkScrolledWindow.Add (this.txtApplicationLicense);
			this.tbsTabs.Add (this.GtkScrolledWindow);
			global::Gtk.Notebook.NotebookChild w8 = ((global::Gtk.Notebook.NotebookChild)(this.tbsTabs [this.GtkScrolledWindow]));
			w8.Position = 1;
			// Notebook tab
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("License");
			this.tbsTabs.SetTabLabel (this.GtkScrolledWindow, this.label3);
			this.label3.ShowAll ();
			// Container child tbsTabs.Gtk.Notebook+NotebookChild
			this.hpaned2 = new global::Gtk.HPaned ();
			this.hpaned2.CanFocus = true;
			this.hpaned2.Name = "hpaned2";
			this.hpaned2.Position = 166;
			// Container child hpaned2.Gtk.Paned+PanedChild
			this.GtkScrolledWindow5 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow5.Name = "GtkScrolledWindow5";
			this.GtkScrolledWindow5.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow5.Gtk.Container+ContainerChild
			this.tvComponents = new global::Gtk.TreeView ();
			this.tvComponents.CanFocus = true;
			this.tvComponents.Name = "tvComponents";
			this.GtkScrolledWindow5.Add (this.tvComponents);
			this.hpaned2.Add (this.GtkScrolledWindow5);
			global::Gtk.Paned.PanedChild w10 = ((global::Gtk.Paned.PanedChild)(this.hpaned2 [this.GtkScrolledWindow5]));
			w10.Resize = false;
			// Container child hpaned2.Gtk.Paned+PanedChild
			this.notebook2 = new global::Gtk.Notebook ();
			this.notebook2.CanFocus = true;
			this.notebook2.Name = "notebook2";
			this.notebook2.CurrentPage = 2;
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Acme Plug-In for Universal Editor</b>");
			this.label13.UseMarkup = true;
			this.vbox4.Add (this.label13);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label13]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Version 5.0");
			this.vbox4.Add (this.label12);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label12]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow4 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow4.Name = "GtkScrolledWindow4";
			this.GtkScrolledWindow4.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow4.Gtk.Container+ContainerChild
			this.textview5 = new global::Gtk.TextView ();
			this.textview5.CanFocus = true;
			this.textview5.Name = "textview5";
			this.GtkScrolledWindow4.Add (this.textview5);
			this.vbox4.Add (this.GtkScrolledWindow4);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow4]));
			w14.Position = 2;
			this.notebook2.Add (this.vbox4);
			// Notebook tab
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Information");
			this.notebook2.SetTabLabel (this.vbox4, this.label6);
			this.label6.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
			this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
			this.tvComponentContributors = new global::Gtk.TreeView ();
			this.tvComponentContributors.CanFocus = true;
			this.tvComponentContributors.Name = "tvComponentContributors";
			this.GtkScrolledWindow3.Add (this.tvComponentContributors);
			this.notebook2.Add (this.GtkScrolledWindow3);
			global::Gtk.Notebook.NotebookChild w17 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.GtkScrolledWindow3]));
			w17.Position = 1;
			// Notebook tab
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Contributors");
			this.notebook2.SetTabLabel (this.GtkScrolledWindow3, this.label7);
			this.label7.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.txtComponentLicense = new global::Gtk.TextView ();
			this.txtComponentLicense.CanFocus = true;
			this.txtComponentLicense.Name = "txtComponentLicense";
			this.GtkScrolledWindow2.Add (this.txtComponentLicense);
			this.notebook2.Add (this.GtkScrolledWindow2);
			global::Gtk.Notebook.NotebookChild w19 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.GtkScrolledWindow2]));
			w19.Position = 2;
			// Notebook tab
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("License");
			this.notebook2.SetTabLabel (this.GtkScrolledWindow2, this.label8);
			this.label8.ShowAll ();
			this.hpaned2.Add (this.notebook2);
			this.tbsTabs.Add (this.hpaned2);
			global::Gtk.Notebook.NotebookChild w21 = ((global::Gtk.Notebook.NotebookChild)(this.tbsTabs [this.hpaned2]));
			w21.Position = 2;
			// Notebook tab
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Components");
			this.tbsTabs.SetTabLabel (this.hpaned2, this.label11);
			this.label11.ShowAll ();
			this.vbox3.Add (this.tbsTabs);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.tbsTabs]));
			w22.Position = 3;
			w1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox3]));
			w23.Position = 0;
			// Internal child UniversalEditor.Engines.GTK.Dialogs.AboutDialog.ActionArea
			global::Gtk.HButtonBox w24 = this.ActionArea;
			w24.Name = "dialog1_ActionArea";
			w24.Spacing = 10;
			w24.BorderWidth = ((uint)(5));
			w24.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w25 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w24 [this.buttonOk]));
			w25.Expand = false;
			w25.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 572;
			this.DefaultHeight = 444;
			this.Show ();
		}
	}
}
