
// This file has been generated by the GUI designer. Do not modify.
namespace UniversalEditor.Engines.GTK
{
	public partial class Editor
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget UniversalEditor.Engines.GTK.Editor
			global::Stetic.BinContainer.Attach (this);
			this.Name = "UniversalEditor.Engines.GTK.Editor";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
