
// This file has been generated by the GUI designer. Do not modify.
namespace UniversalEditor.Editors.UnrealEngine.Package
{
	public partial class UnrealPackageEditor
	{
		private global::Gtk.Notebook notebook2;
		private global::Gtk.Label label2;
		private global::Gtk.Label label3;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView tvExport;
		private global::Gtk.Label label4;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget UniversalEditor.Editors.UnrealEngine.Package.UnrealPackageEditor
			global::Stetic.BinContainer.Attach (this);
			this.Name = "UniversalEditor.Editors.UnrealEngine.Package.UnrealPackageEditor";
			// Container child UniversalEditor.Editors.UnrealEngine.Package.UnrealPackageEditor.Gtk.Container+ContainerChild
			this.notebook2 = new global::Gtk.Notebook ();
			this.notebook2.CanFocus = true;
			this.notebook2.Name = "notebook2";
			this.notebook2.CurrentPage = 2;
			// Notebook tab
			global::Gtk.Label w1 = new global::Gtk.Label ();
			w1.Visible = true;
			this.notebook2.Add (w1);
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Name Table");
			this.notebook2.SetTabLabel (w1, this.label2);
			this.label2.ShowAll ();
			// Notebook tab
			global::Gtk.Label w2 = new global::Gtk.Label ();
			w2.Visible = true;
			this.notebook2.Add (w2);
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Import Table");
			this.notebook2.SetTabLabel (w2, this.label3);
			this.label3.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvExport = new global::Gtk.TreeView ();
			this.tvExport.CanFocus = true;
			this.tvExport.Name = "tvExport";
			this.GtkScrolledWindow.Add (this.tvExport);
			this.notebook2.Add (this.GtkScrolledWindow);
			global::Gtk.Notebook.NotebookChild w4 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.GtkScrolledWindow]));
			w4.Position = 2;
			// Notebook tab
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Export Table");
			this.notebook2.SetTabLabel (this.GtkScrolledWindow, this.label4);
			this.label4.ShowAll ();
			this.Add (this.notebook2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
